name: Apollo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd apollo
          cargo build --verbose
      - name: Run tests
        run: |
          cd apollo
          cargo test --verbose
