name: hemes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev build-essential libpango1.0-dev libgraphene-1.0-dev pkg-config
    # - name: Set PKG_CONFIG_PATH
    #   run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
    - name: Build
      run: |
        cd hermes
        sudo apt-get update && sudo apt-get install -y libgtk-4-dev build-essential libpango1.0-dev libgraphene-1.0-dev pkg-config
        cargo build --verbose
    - name: Run tests
      run: |
        cd hermes
        sudo apt-get update && sudo apt-get install -y libgtk-4-dev build-essential libpango1.0-dev libgraphene-1.0-dev pkg-config
        cargo test --verbose

